server:
  port: 8888
#spring:
#  cloud:
#    config:
#      discovery:
#        enabled: true
#      server:
#        encrypt:
#          enabled: false
#        git:
#          uri: https://github.com/zdylan/config-repo.git
#          search-paths: licensingservice, organizationservice

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/dylan/IdeaProjects/mcs-chapter4/confsvr/src/main/resources/config
